Vagrant.configure("2") do |config|
    config.vm.box = "generic/opensuse15"
    config.vm.network "private_network", ip: "192.168.56.4"
    config.vm.network "forwarded_port", guest: 5900, host: 5900
    config.vm.synced_folder "./guest_mount", "/vagrant", type: "nfs"
    config.vm.hostname = "libvirthost"
    config.vm.provider "virtualbox" do |v|
        v.name = "libvirthost"
        # v.gui = true
        v.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
        v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
        v.memory = 4096
        v.cpus = 4
    end
    config.vm.provision "shell", path: "configure.sh"
end