if RbConfig::CONFIG['host_os'].match?(/^darwin/)
    nfs_proto = 'udp'
    nfs_vers = 3
else
    nfs_proto = 'tcp'
    nfs_vers = 4
end

Vagrant.configure("2") do |config|
    config.vm.box = "generic/opensuse15"
    config.vm.network "private_network", ip: "192.168.56.4"
    config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_udp: nfs_proto, nfs_version: nfs_vers
    config.vm.hostname = "libvirthost"
    config.vm.provider "virtualbox" do |v|
        v.name = "libvirthost"
        #v.gui = true
        v.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
        v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
        v.customize ["modifyvm", :id, "--chipset", "ich9"]
        v.memory = 8192
        v.cpus = 4
    end
    config.vm.provision "shell", path: "configure.sh"
end

