REQUIRED_PLUGINS = %w(vagrant-libvirt)
exit unless REQUIRED_PLUGINS.all? do |plugin|
  Vagrant.has_plugin?(plugin) || (
    puts "The #{plugin} plugin is required. Please install it with:"
    puts "$ vagrant plugin install #{plugin}"
    false
  )
end

KEYFILE = File.join(__dir__, '..', 'libvirt_host', '.vagrant', 'machines', 'default', 'virtualbox', 'private_key')
REMOTE_HOST = '192.168.56.4'
# Boot params collected from ncn-w001:/metal/recovery/boot/grub2/grub.cfg
# Unused boot params collected here for reference only.
UNUSED_BOOT_PARAMS = %w(
  bond=bond0:mgmt0,mgmt1:mode=802.3ad,xmit_hash_policy=layer2+3,lacp_rate=slow
  biosdevname=1
  ifname=hsn0:ec:0d:9a:d9:c4:5a
  ip=hsn0:auto6
  ifname=lan1:b8:59:9f:f9:27:e3
  ip=lan1:auto6
  ifname=lan0:b8:59:9f:f9:27:e2
  ip=lan0:auto6
  ifname=mgmt0:a4:bf:01:38:e9:36
  ip=mgmt0:auto6
  ifname=mgmt1:a4:bf:01:38:e9:37
  ip=mgmt1:auto6
  pcie_ports=native
  rootfallback=LABEL=BOOTRAID
  initrd=initrd.img.xz
  ds=nocloud-net\;s=http://10.1.1.2:8888/\;h=ncn-w001
  rd.live.squashimg=filesystem.squashfs
  rd.live.overlay=LABEL=ROOTRAID
  rd.live.overlay.thin=1
  rd.live.overlay.overlayfs=1
  rd.live.ram=0
  rd.writable.fsimg=0
  root=live:LABEL=SQFSRAID
  transparent_hugepage=never
  console=tty0
  console=ttyS0,115200
  rd.md.waitclean=1
  rd.md.conf=1
  rd.net.timeout.carrier=120
  rd.net.timeout.ifup=120
  rd.net.timeout.iflink=120
  rd.net.dhcp.retry=5
  rd.net.timeout.ipv6auto=0
  rd.net.timeout.ipv6dad=0
)
BOOT_PARAMS = %w(
  iommu=pt
  rd.skipfsck
  rd.luks=0
  rd.luks.crypttab=0
  rd.lvm.conf=0
  rd.lvm=1
  rd.auto=1
  rd.md=1
  rd.dm=0
  rd.neednet=0
  rd.peerdns=0
  rd.multipath=0
  rd.bootif=0
  hostname=ncn-w001
  append nosplash
  crashkernel=360M
  log_buf_len=1
  rd.retry=10
  rd.shell
  xname=x3000c0s7b0n0
  metal.no-wipe=1
  metal.disks=1
  root=/dev/vda2
)

Vagrant.configure("2") do |config|
    # config.vm.box = "generic/ubuntu2010" # This boots.
    # config.vm.box = "generic/opensuse15" # This boots into an emergency shell.
    config.vm.box = "k8s_ncn" # This stops at a blinking cursor right after the opensuse splash screen.
    config.vm.hostname = "k8s-ncn"
    config.vm.boot_timeout = 600
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    config.vm.provider :libvirt do |libvirt|
        libvirt.default_prefix = "csm-"
        libvirt.graphics_type = "vnc"
        libvirt.graphics_ip = "0.0.0.0"
        libvirt.graphics_port = "5900"
        # libvirt.serial :type => "file", :source => {:path => "/var/log/ncn_k8s.log"}
        libvirt.kernel = '/vagrant/boot/k8s_ncn.kernel'
        libvirt.initrd = '/vagrant/boot/k8s_ncn_initrd.xz'
        libvirt.cmd_line = BOOT_PARAMS.join(' ')
        libvirt.cpus = 2
        libvirt.memory = 2048
        libvirt.machine_type = 'q35'
        libvirt.uri = "qemu+ssh://root@#{REMOTE_HOST}/session?keyfile=#{KEYFILE}"
        libvirt.system_uri = "qemu+ssh://root@#{REMOTE_HOST}/system?keyfile=#{KEYFILE}"
    end
    # config.vm.provision "ansible_local" do |ansible|
    #     ansible.playbook = "playbook.yml"
    # end
end